# Generated by Django 3.1.1 on 2020-09-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Primeiro nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='Restante do nome')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acao.endereco')),
            ],
        ),
    ]
