# Generated by Django 3.1.1 on 2020-09-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Primeiro nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='Restante do nome')),
                ('cidade', models.CharField(default='1', max_length=80, verbose_name='Cidade em que reside')),
                ('bairro', models.CharField(default='1', max_length=80, verbose_name='Bairro em que reside')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
