# Generated by Django 3.1.1 on 2020-09-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='bairro',
            field=models.CharField(max_length=80, verbose_name='Bairro em que reside'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='cidade',
            field=models.CharField(max_length=80, verbose_name='Cidade em que reside'),
        ),
    ]
