# Generated by Django 3.1.1 on 2020-09-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=80, verbose_name='Cidade em que reside')),
                ('bairro', models.CharField(max_length=80, verbose_name='Bairro em que reside')),
                ('endereco', models.CharField(blank=True, max_length=80, null=True, verbose_name='Endereço em que reside')),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da ação')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Nome da instituição que está organizando')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acao.endereco')),
            ],
        ),
    ]
