# Generated by Django 3.1.1 on 2020-09-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='local',
        ),
        migrations.AddField(
            model_name='acao',
            name='bairro',
            field=models.CharField(default='1', max_length=80, verbose_name='Bairro em que reside'),
        ),
        migrations.AddField(
            model_name='acao',
            name='cidade',
            field=models.CharField(default='1', max_length=80, verbose_name='Cidade em que reside'),
        ),
        migrations.AddField(
            model_name='acao',
            name='endereco',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Endereço em que reside'),
        ),
    ]
