# Generated by Django 3.1.1 on 2020-09-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0002_auto_20200917_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='bairro',
            field=models.CharField(max_length=80, verbose_name='Bairro em que reside'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='cidade',
            field=models.CharField(max_length=80, verbose_name='Cidade em que reside'),
        ),
    ]
